#!/bin/bash

set -e

source init-kubectl

log-info "Test: broker fetches target-pod SVID via KubernetesObjectReference (pods/core)"

./bin/kubectl -nspire exec -t broker -- /brokerclient \
    -ref-type object \
    -plural pods -group core \
    -namespace spire -name target-pod \
    -expected-spiffe spiffe://example.org/target-pod \
    || fail-now "broker failed to fetch SVID via pod object reference"

log-success "broker fetched target-pod SVID via KubernetesObjectReference"
