#!/bin/bash

set -e

source init-kubectl

log-info "Test: broker allowed to use object references is denied by Kubernetes authorization"

./bin/kubectl -nspire exec -t rbac-denied-broker -- /brokerclient \
    -ref-type object \
    -plural pods -group core \
    -namespace spire -name target-pod \
    -expect-err PermissionDenied \
    || fail-now "rbac-denied-broker did not get PermissionDenied from Kubernetes authorization"

log-success "rbac-denied-broker rejected by Kubernetes authorization as expected"

log-info "Test: broker allowed to use PID references is denied by Kubernetes authorization"

TARGET_PID=$(./bin/kubectl -nspire exec -t rbac-denied-broker -- sh -c \
    "ps -ef | grep '[s]pire-agent api watch' | awk '{print \$1}' | head -n1")

if [ -z "${TARGET_PID}" ]; then
    fail-now "could not resolve target-pod PID from rbac-denied-broker"
fi

./bin/kubectl -nspire exec -t rbac-denied-broker -- /brokerclient \
    -ref-type pid \
    -pid "${TARGET_PID}" \
    -expect-err PermissionDenied \
    || fail-now "rbac-denied-broker PID reference did not get PermissionDenied from Kubernetes authorization"

log-success "rbac-denied-broker PID reference rejected by Kubernetes authorization as expected"
